### ISSUE TITLE
AssertationError

### ISSUE THREAD

**Issue by aczy118** [prajjwal1/autonomous-object-detection#5] opened 2020-03-29 22:11 UTC
Hi,

I was trying to follow object detection repository and run it myself for BDD dataset but I keep getting the same error. I looked for it online but I could not find any answer and since I am an amateur I was hoping you could help me. It would be much appreciated if you could share your knowledge and enlighten me. I am sending you below the output I get when try to run it. By the way I am using PyTorch version 1.4.0 and torchvision version 0.5.0.

 

Loading Files

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████| 69863/69863 [00:02<00:00, 31450.21it/s]

Loading Done

Model Initialization

  0%|                                                                                                                           | 0/24 [00:00<?, ?it/s]Traceback (most recent call last):

  File "train_baseline.py", line 64, in <module>

    train_one_epoch(model, optimizer, dl, device, epoch, print_freq = 200)

  File "C:\Users\Burak\engine.py", line 30, in train_one_epoch

    loss_dict = model(images, targets)

  File "C:\Users\Burak\AppData\Local\Continuum\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__

    result = self.forward(*input, **kwargs)

  File "C:\Users\Burak\AppData\Local\Continuum\anaconda3\lib\site-packages\torchvision\models\detection\generalized_rcnn.py", line 71, in forward

    detections, detector_losses = self.roi_heads(features, proposals, images.image_sizes, targets)

  File "C:\Users\Burak\AppData\Local\Continuum\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__

    result = self.forward(*input, **kwargs)

  File "C:\Users\Burak\AppData\Local\Continuum\anaconda3\lib\site-packages\torchvision\models\detection\roi_heads.py", line 745, in forward

    assert t["labels"].dtype == torch.int64, 'target labels must of int64 type'

**AssertionError: target labels must of int64 type**

**Comment by prajjwal1** [comment] 2020-03-30 04:00
I think this is pretty straightforward. As torchvision specifies `target labels must of int64 type`. This means that when you're passing targets here:
`loss_dict = model(images, targets)
`
`targets` tensor is not of the type `int64`. This can simply be fixed by casting the tensor to another tensor type. So by doing:
`
targets = targets.type(torch.int64) 
`
`targets` will casted into `torch.int64` tensor type.
I think making this change will make the assertion error go away.

**Comment by aczy118** [comment] 2020-03-30 12:46
Hi again,

Thanks for the quick response. However, when I

**Comment by aczy118** [comment] 2020-03-31 13:30
Hi again,

I added the line to engine.py as you said but this time I got this error:

File "train_baseline.py", line 64, in <module>
    train_one_epoch(model, optimizer, dl, device, epoch, print_freq = 200)
  File "C:\Users\Burak\engine.py", line 31, in train_one_epoch
    targets = targets.type(torch.int64)
AttributeError: 'list' object has no attribute 'type'

I was thinking I might have made a mistake or missed something while trying to follow your repository. So I cloned it and tried to run it without changing anything (only the cfg.py) , but again I am getting the same errors. Do you have any idea what might be the reason? Thanks in advance.

**Comment by prajjwal1** [comment] 2020-03-31 13:34
When I wrote the code, I was using Pytorch 1.1. This is a simple error. Maybe something might have changed in between. Anyways, from what I can see, I think you have a list of tensors. So you can loop through the list and apply the `type` operation on the elements of the list. For ex.
```
for t in targets:
    t = t.type(torch.int64)
```
These operations are Pytorch specific so they can only be applied on Tensors not Python objects. I hope this helps. You can find more info on [Pytorch forums](discuss.pytorch.org).

**Comment by prajjwal1** [comment] 2020-04-02 06:08
I hope the issue is fixed. Reopen it if you think it's still not resolved.

**Closed as completed by prajjwal1** 2020-04-02 06:08 UTC
